# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-23 18:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamestore', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
