# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-24 22:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamestore', '0002_game_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='price',
            field=models.CharField(default='', max_length=50),
        ),
    ]
